# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
xcode_workspace: Example/NumericPicker.xcworkspace
xcode_scheme: Example/NumericPicker-Example
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --no-document
- gem install xcpretty --no-document
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/NumericPicker.xcworkspace -scheme NumericPicker-Example -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
