# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
xcode_workspace: Example/NumericPicker.xcworkspace
xcode_scheme: Example/NumericPicker-Example
cache:
 - bundler
 - cocoapods
podfile: Example/Podfile
before_install:
- rvm use 2.3.1
- gem install cocoapods --no-document
- gem install xcpretty --no-document
- pod install --project-directory=Example --repo-update
script:
- set -o pipefail && travis_retry xcodebuild test -workspace Example/NumericPicker.xcworkspace -scheme NumericPicker-Example -destination 'platform=iOS Simulator,name=iPhone 7s,OS=10.3' ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
