# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
xcode_project: NumericPicker.xcodeproj
xcode_scheme: NumericPicker
cache:
 - bundler
 - xcpretty
before_install:
 - gem install xcpretty --no-document
script:
 - set -o pipefail && travis_retry xcodebuild test -project NumericPicker.xcodeproj -scheme NumericPicker -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' ONLY_ACTIVE_ARCH=NO | xcpretty
