# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
xcode_workspace: Example/NumericPicker.xcworkspace
xcode_scheme: Example/NumericPicker_Example
cache: cocoapods
podfile: Example/Podfile
before_install:
- rvm get stable --auto-dotfiles
- gem install cocoapods --no-document
- gem install xcpretty --no-document
- pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -workspace Example/NumericPicker.xcworkspace -scheme NumericPicker-Example -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 4s,OS=9.3' ONLY_ACTIVE_ARCH=NO | xcpretty
@#- pod lib lint
